import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import HomeContainer from '../container/Home'
import styles from '../styles/Home.module.css'
import axios from "axios";
import { UserData } from './api/user';
import { initializeStore } from '../store';


const Home: NextPage = ({ }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        < HomeContainer />
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async context => {
  const zustandStore = initializeStore();

  let state = zustandStore.getState();

  const { data: {
    user,
    projects,
    techs,
    experiences,
    socialMedias
  } }: { data: UserData } = await axios.get('http://localhost:3000/api/user');

  state = {
    ...state,
    user,
    projects,
    techs,
    experiences,
    socialMedias
  }


  return { props: { initialZustandState: JSON.parse(JSON.stringify(state)) } }
}


export default Home
